// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCtYdX_i7uJf6DxLQ_u5X9HlDB4PEk6TY',
    appId: '1:450414670000:web:175a3885c206ffcfac0b75',
    messagingSenderId: '450414670000',
    projectId: 'gpt-quiz-flutter',
    authDomain: 'gpt-quiz-flutter.firebaseapp.com',
    storageBucket: 'gpt-quiz-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqOINNr7niIWooqa98npmJhLmeSmo5sSw',
    appId: '1:450414670000:android:e9d72247458a6b22ac0b75',
    messagingSenderId: '450414670000',
    projectId: 'gpt-quiz-flutter',
    storageBucket: 'gpt-quiz-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ4rJ1bUMiXjTtANdMXDa4rzQ49QDoI4Q',
    appId: '1:450414670000:ios:2187acf80894dea7ac0b75',
    messagingSenderId: '450414670000',
    projectId: 'gpt-quiz-flutter',
    storageBucket: 'gpt-quiz-flutter.appspot.com',
    iosClientId: '450414670000-9jkvab76122ln1sjt8c8mrvpv9h50eks.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizCraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ4rJ1bUMiXjTtANdMXDa4rzQ49QDoI4Q',
    appId: '1:450414670000:ios:66a4783c6cf9657cac0b75',
    messagingSenderId: '450414670000',
    projectId: 'gpt-quiz-flutter',
    storageBucket: 'gpt-quiz-flutter.appspot.com',
    iosClientId: '450414670000-3v82c27g6vdig2oqebnk6d3kpmep8vub.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizCraft.RunnerTests',
  );
}
